name: "appflowy_editor"

version: 6.1.0

homepage: "https://github.com/AppFlowy-IO/appflowy-editor"

environment:
  sdk: ">=3.10.0-290.4.beta <4.0.0"
  flutter: ">=3.38.0"

description: A highly customizable rich-text editor for Flutter. The AppFlowy
  Editor project for AppFlowy and beyond.

dependencies:
  collection: "^1.19.1"
  device_info_plus: "^12.2.0"
  diff_match_patch: "^0.4.1"
  file_picker: ^10.3.6
  flutter:
    sdk: flutter
  flutter_svg: "^2.2.2"
  html: ^0.15.6
  http: "^1.6.0"
  intl: "^0.20.2"
  keyboard_height_plugin: "^0.1.5"
  logging: "^1.3.0"
  markdown: "^7.3.0"
  # nanoid: "^1.0.0"
  numerus: "^2.3.0"
  pdf: "^3.11.3"
  provider: "^6.1.5+1"
  scroll_to_index: "^3.0.1"
  string_validator: "^1.2.0"
  universal_html: "^2.2.4"
  universal_platform: ^1.1.0
  url_launcher: "^6.3.2"

  equatable: ^2.0.7
  flutter_animate: ^4.5.2
  # scrollview_observer: ^1.26.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl_utils: "^2.8.12"
  mockito: "^5.5.1"
  network_image_mock: "^2.1.1"
  path_provider: "^2.1.5"
  pubspec_dependency_sorter: "^1.0.5"

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

topics:
  - widgets
  - editor
  - appflowy

flutter:
  assets:
    - "assets/images/toolbar/"
    - "assets/images/selection_menu/"
    - "assets/images/image_toolbar/"
    - "assets/images/"
    - "assets/mobile/toolbar_icons/"

flutter_intl:
  enabled: true
  class_name: AppFlowyEditorLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/src/l10n
  use_deferred_loading: false
  localizely:
    project_id: b7199c7d-eca0-4025-894d-230cdcafa9aa
